const ChartsConfig = [
  // ─── GERAL ────────────────────────────────────────────────────────────────
  {
    id: 'geral-idades',
    title: 'Distribuição de Idades',
    question: 'IDADE',
    categories: ['geral'],
    type: 'donnut',
    order: ['17 - 19', '20 - 21', '21 - 22', '23 - 24', '25 +'],
  },
  {
    id: 'geral-semestres',
    title: 'Distribuição de Semestres',
    question: 'SEMESTRE',
    categories: ['geral'],
    type: 'donnut',
    order: ['1 - 2', '3 - 4', '5 - 6', '7 - 8', '9 - 10'],
  },
  {
    id: 'geral-cursos',
    title: 'Distribuição de Cursos',
    question: 'CURSO',
    categories: ['geral'],
    type: 'pie',
  },
  {
    id: 'idade-bar-semestre', 
    title: 'Distribuição de idades por semestre',
    question: 'IDADE',
    questionB: 'SEMESTRE',
    categories: ['geral'],
    type: 'bar',
    orderX: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
    orderY: ['1 - 2', '3 - 4', '5 - 6', '7 - 8', '9 - 10'],
    eixoX:"Idade",
    typsB:"Semestre"
  },


  // ─── DESEMPENHO ───────────────────────────────────────────────────────────
  {
    id: 'horas-desempenho', 
    title: 'Horas de estudo × Desempenho acadêmico',
    question: 'HORAS',
    questionB: 'DESEMPENHO',
    categories: ['desempenho'],
    type: 'bar',
    orderX: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
    orderY: ['Bom', 'Médio', 'Ruim'],
    eixoX:"Horas de estudo",
    typsF:"Desepenho",
  },
  {
    id: 'scatter-horas-estresse-desempenho',
    title: 'Falta de sono × Estresse (por desepenho)',
    questionX: 'SONO',
    questionY: 'ESTRESSE',
    groupBy: 'DESEMPENHO',
    categories: ['desempenho'],
    orderX: ['Nunca', 'Raramente', 'Às vezes', 'Frequentemente', 'Sempre'],
    orderY: ['Nunca', 'Raramente', 'Às vezes', 'Frequentemente', 'Sempre'],
    order:['Médio', 'Bom', 'Ruim'],
    eixoX:"Nivel de falta de sono",
    eixoY:"Nivel de Estresse",
    type: 'scatter',
    typsF:"Desepenho",
  },
  {
    id: 'carga-desempenho', 
    title: 'Sobrecarga de estudos × Desempenho acadêmico',
    question: 'CARGA',
    questionB: 'DESEMPENHO',
    categories: ['desempenho'],
    type: 'line',
    orderX: ['Não','Às vezes', 'Sim'],
    orderY: ['Bom', 'Médio', 'Ruim'],
    eixoX:"Sobrecarga",
    typsF:"Desepenho",
  },
  {
    id: 'mudanca-desempenho',
    title: 'Autoavaliação do desempenho dos estudantes',
    question: 'DESEMPENHO',
    categories: ['desempenho'],
    type: 'pie',
    order: ['Sim', 'Não'],
  },
  {
    id: 'heatmap-estresse-sono-desempenho',
    title: 'Estresse × Horas de estudo',
    question: 'HORAS',
    questionB: 'SONO',
    categories: ['desempenho'],
    orderX: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
    orderY: ['Nunca', 'Raramente', 'Às vezes', 'Frequentemente', 'Sempre'],
    type: 'heatmap',
    typsF:"Horas de estudo",
    typsB:"Estresse",
  },
    {
    id: 'deixoudefazer-desempenho', 
    title: 'Falta de atividades por questões emocionais vs desempenho',
    question:'DESEMPENHO',
    questionB:'DEIXOU',
    categories: ['desempenho'],
    type: 'line',
    orderX:['Ruim', 'Médio', 'Bom'],
    orderY: ['Não', 'Sim'],
    eixoX:"Desepenho",
    typsB:"deixou de fazer atividades",
  },

  // ─── HÁBITOS ──────────────────────────────────────────────────────────────
  {
    id: 'tarefas-estresse-habitos', 
    title: 'Sente tarefas demais para a disponibilidade × Frequência de Estresse',
    question: 'TAREFAS',
    questionB: 'ESTRESSE',
    categories: ['habitos'],
    type: 'bar',
    orderX:['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    orderY:['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
  },
  {
    id: 'Sono-PIES-habitos', 
    title: 'Dificuldade para dormir devido a preocupações acadêmicas',
    question: 'SONO',
    categories: ['habitos'],
    type: 'pie',
    order:['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
  },
  {
    id: 'ESTUDO-donnut-habitos', 
    title: 'Horas dedicadas aos estudos por dia',
    question: 'HORAS',
    categories: ['habitos'],
    type: 'donnut',
    order: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
  },
  {
    id: 'ESTUDO-x-carga-habitos',
    title: 'Horas de estudo × Sentimento de sobrecarga',
    question: 'HORAS',
    questionB: 'CARGA',
    categories: ['habitos'],
    orderX: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
    orderY: ['Sim','Às vezes', 'Não'],
    type: 'heatmap',
  },
  {
    id: 'desempenho-estresse-habitos', 
    title: 'Mudança no seu desempenho relacionada a ansiedade x Horas de estudo',
    question: 'MUDANCA',
    questionB: 'HORAS',
    categories: ['habitos'],
    type: 'bar',
    orderX: ['Sim', 'Não'],
    orderY: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
  },
  {
    id: 'desempenho-estresse-habitos-LINE',
    title: 'Horas de estudo x Estresse',
    question: 'ESTRESSE',
    questionB: 'HORAS',
    categories: ['habitos'],
    type: 'line',
    orderX: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    orderY: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
  },


  // ─── PERFIL ───────────────────────────────────────────────────────────────
  {
    id: 'radar-trabalha-perfil',
    title: 'Perfil de bem-estar: Trabalha vs Não trabalha',
    groupBy: 'TRABALHA',
    axes: [
      { question: 'ESTRESSE',     label: 'Estresse' },
      { question: 'SONO',         label: 'Sono' },
      { question: 'CARGA',        label: 'Carga' },
      { question: 'TAREFAS',      label: 'Tarefas' },
      { question: 'BEM_ESTAR',    label: 'Bem-estar' },
      { question: 'MUDANCA',      label: 'Mudança de desempenho' },
    ],
    categories: ['perfil'],
    order: ['Sim', 'Não'],
    type: 'radar',
  },
  {
    id: 'radar-semestre-perfil',
    title: 'Perfil de estresse por semestre',
    groupBy: 'SEMESTRE',
    axes: [
      { question: 'ESTRESSE',     label: 'Estresse' },
      { question: 'ANSIEDADE_PZ', label: 'Ansiedade' },
      { question: 'SONO',         label: 'Sono' },
      { question: 'CARGA',        label: 'Carga' },
    ],
    categories: ['perfil'],
    order: ['1 - 2', '3 - 4', '5 - 6', '7 - 8', '9 - 10'],
    type: 'radar',
  },
  {
    id: 'scatter-semestre-estresse-perfil',
    title: 'Semestre atual × Estresse (por horas de estudo)',
    questionX: 'SEMESTRE',
    questionY: 'HORAS',
    groupBy: 'ESTRESSE',
    categories: ['perfil'],
    orderX: ['1 - 2', '3 - 4', '5 - 6', '7 - 8', '9 - 10'],
    orderY: ['1 - 2 h', '3 - 4 h', '5 - 6h','7h +'],
    order: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    type: 'scatter',
  },
  {
    id: 'trabalha-idade-perfil', 
    title: 'Estudantes trabalham ? x Idade',
    question: 'TRABALHA',
    questionB: 'IDADE',
    categories: ['perfil'],
    type: 'bar',
    orderX: ['Sim', 'Não'], 
    orderY: ['17 - 19', '20 - 21', '21 - 22', '23 - 24', '25 +'],
  },
  {
    id: 'trabalha-perfil',
    title: 'Estudantes trabalham ?',
    question: 'TRABALHA',
    categories: ['geral', 'perfil'],
    type: 'pie',
    order: ['Sim', 'Não'],
  },
  {
    id: 'stacked-semestre-estresse-perfil',
    title: 'Distribuição de estresse por semestre (%)',
    question: 'SEMESTRE',
    questionB: 'ESTRESSE',
    categories: ['perfil'],
    type: 'stackedbar',
    orderX: ['1 - 2', '3 - 4', '5 - 6', '7 - 8', '9 - 10'],
    orderY: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    eixoX: 'Semestre',
    eixoY: 'Proporção (%)',
    typsF: '',
    typsB: '',
  },

  // ─── EMOCIONAL ────────────────────────────────────────────────────────────
  {
    id: 'ansiedade-bemestar-emocional', 
    title: 'Sentimento de ansiedade com prazos × Bem-estar emocional afetado',
    question: 'ANSIEDADE_PZ',
    questionB: 'BEM_ESTAR',
    categories: ['emocional'],
    type: 'bar',
    orderX:['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    orderY: ['Muito', 'Moderadamente', 'Pouco', 'Nada'],
  },
  {
    id: 'deixou-atividade-emocional',
    title: 'Deixou alguma atividade por problemas emocionais?',
    question: 'DEIXOU',
    categories: ['emocional'],
    type: 'pie',
    order: ['Sim', 'Não'],
  },
  {
    id: 'heatmap-emocional-carga-emocional',
    title: 'Deixou de fazer atividade por problemas emocionais × Sobrecarga de estudos',
    question: 'DEIXOU',
    questionB: 'CARGA',
    categories: ['emocional'],
    orderX: ['Sim', 'Não'],
    orderY: ['Sim', 'Às vezes', 'Não'],
    type: 'heatmap',
  },
  {
    id: 'heatmap-emocional-carga-2',
    title: 'Dificuldade para dormir × Sentimento de sobrecarga',
    question: 'SONO',
    questionB: 'CARGA',
    categories: ['emocional'],
    orderX: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    orderY: ['Sim', 'Às vezes', 'Não'],
    type: 'heatmap',
  },
  {
    id: 'frequencia-ansiedade-emocional',
    title: 'Frequência de ansiedade/estresse',
    question: 'ESTRESSE',
    categories: ['emocional'],
    type: 'donnut',
    order:['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
  },
  {
    id: 'stacked-bemestar-ansiedade-emocional',
    title: 'Impacto emocional no bem-estar por nível de ansiedade (%)',
    question: 'ANSIEDADE_PZ',
    questionB: 'BEM_ESTAR',
    categories: ['emocional'],
    type: 'stackedbar',
    orderX: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
    orderY: ['Muito', 'Moderadamente', 'Pouco', 'Nada'],
    eixoX: 'Frequência de ansiedade',
    eixoY: 'Proporção (%)',
    typsF: '',
    typsB: '',
  },

  // ─── AJUDA ────────────────────────────────────────────────────────────────
  {
    id: 'busca-suporte-ajuda', 
    title: 'Suporte da instituição x Impedimento ao buscar ajuda',
    question: 'BUSCA_AJUDA2',
    questionB: 'SUPORTE',
    categories: ['ajuda'],
    type: 'bar',
    orderX: ['Sim', 'Parcialmente', 'Não'],
    orderY: [],
  },
  {
    id: 'impede-ajuda',
    title: 'O que impede de buscar ajuda?',
    question: 'SUPORTE',
    categories: ['ajuda'],
    type: 'pie',
  },
  {
    id: 'busca-ajuda',
    title: 'Costuma buscar ajuda?',
    question: 'BUSCA_AJUDA1',
    categories: ['ajuda'],
    type: 'pie',
    order: ['Sim, profissional', 'Sim, apoio de amigos ou família', 'Não costumo buscar ajuda'],
  },
  {
    id: 'instituicao-ajuda',
    title: 'Recebeu suporte da instituição?',
    question: 'BUSCA_AJUDA2',
    categories: ['ajuda'],
    type: 'pie',
    order: ['Sim', 'Parcialmente', 'Não'],
  },
  {
    id: 'busca-suporte-ajuda-2', 
    title: 'Recebeu suporte da instituição x Costuma buscar ajuda',
    question: 'BUSCA_AJUDA2',
    questionB: 'BUSCA_AJUDA1',
    categories: ['ajuda'],
    type: 'bar',
    orderX: ['Sim', 'Parcialmente', 'Não'],
    orderY: ['Sim, profissional', 'Sim, apoio de amigos ou família', 'Não costumo buscar ajuda'],
  },
]

export default ChartsConfig